### ISSUE TITLE
Alternative array-definition missing in spec

### ISSUE THREAD

**Issue by etse** [holgerl/hilvl#3]
In the online evaluator the code uses the following array definition;

``` ruby
# new foo = 
    1, 2, 3
```

The spec only describes the following syntax: 

``` ruby
# new foo = 
    1
    2
    4
```

**Comment by holgerl** [comment]
This is actually a topic for discussion. The reason for not documenting the comma array declaration is because I am not shure if it should be a part of the language, or if the functionality should be provided in another way.

An important goal here is the ability to have a consise way of declaring an array, since the newline approach takes a lot of space. On the other hand, maybe the comma way should be the ONLY way, so that newlines are not part of the syntax.

**Comment by etse** [comment]
What about making the comma an action on the array service. Taking 1 argument and appending it to the array and returning itself. Allowing for chaining.

**Comment by holgerl** [comment]
That is a good suggestion. The drawback, however, will be that code blocks must then have a lot of parantheses:

```
OnEvent click
    (Score increase 1) ,
    (Player move up) ,
    (Foo bar baz)
```

The advantage is that this is an even simpler syntax than the newline based.

**Comment by holgerl** [comment]
A version of @etse's suggestion is now implemented in the language. It is documented in README.md. The benefit of this is that no new syntax is added. It is all services and actions. The previous special handling of comma is removed from the tokenizer. The drawback is that the newline and tab syntax is still necessary. But many languages rely on whitespace as part of the syntax, like Python and Haskell.

#### The `,` action

There is a convenient action `,` on strings, numbers and booleans. It returns a list containing the value and the argument:

``` javascript
1, 2 // This is the list [1,2]
"one", "two" // This is the list ["one","two"]
true, false // This is the list [true,false]
```

A clever trick is that the List service also has a `,` action that returns a new list with the argument added. So it is possible to chain this with several elements:

``` javascript
@ var myList = ("foo", "bar", "baz", "hello")
```
